### ISSUE TITLE
Metamask, Walletconnect Connectors no longer valid?

### ISSUE THREAD

**Issue by CRYPTO-GENIK** [sveeeth/sveeeth#23]
`    import { InjectedConnector, MetaMaskConnector  } from "sveeeth/connectors";`
    
    From the Example in the readme doesn't work : I think WAGMI has moved the references to their connectors and restructured them.

**Comment by tohodakilla** [comment]
I have the same issue. I can offer bounty for fixing that. Please name price and give crypto wallet.

**Comment by CRYPTO-GENIK** [comment]
I see the values from wagmi are just passed through so I tapped WAGMI directly, this was more to notify the developer that they need to address this issue

**Comment by tohodakilla** [comment]
did the same, thanks.

**Comment by 0xbarbs** [comment]
Thanks for reporting, I'll implement a fix for this soon

**Comment by 0xbarbs** [comment]
Fixed in #28
