### ISSUE TITLE
State Refactoring

### ISSUE THREAD

**Issue by CRYPTO-GENIK** [sveeeth/sveeeth#24]
I was thinking about the State being three Bool values and it would probably be better to have a single "WalletConnectorState" that could be multiple values, that way there's way that the state could be both connecting = true and connected = true at the same time.

**Comment by 0xbarbs** [comment]
I'll look at adding an `isConnecting` boolean to the account store, it looks like this is supported in the underlying wagmi core [getAccount](https://wagmi.sh/core/actions/getAccount) action already.

**Comment by 0xbarbs** [comment]
Implemented in #29
